# Generated by Django 5.1.1 on 2024-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexam',
            name='msisdn',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='marks_per_question',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
