# Generated by Django 5.1.1 on 2024-11-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='question_difficulty_levels',
        ),
    ]
